export const ALLOWED_DISH_CUISINES = [
  'Syrian',
  'Middle Eastern',
  'Western',
  'Greek',
  'Mediterranean',
  'Italian',
  'Mexican',
  'Asian',
  'Indian',
  'Japanese',
  'Korean',
  'Thai',
  'Turkish',
] as const;

export type DishCuisineStyle = (typeof ALLOWED_DISH_CUISINES)[number];
export type CookingMethod = 'grill' | 'stir-fry' | 'braise' | 'roast' | 'raw' | 'steam' | 'bake' | 'saute';

export type DishBlueprint = {
  name: string;
  cuisineStyle: DishCuisineStyle;
  cookingMethod: CookingMethod;
  mealTypes: Array<'BREAKFAST' | 'LUNCH' | 'DINNER' | 'SNACK'>;
  famous: boolean;
  proteins: string[];
  carbs: string[];
  keyIngredients: string[];
  bannedIngredients?: string[];
};

export const FAMOUS_DISHES: DishBlueprint[] = [
  // ─── SYRIAN ───────────────────────────────────────────────────────────────
  {
    name: 'Shish tawook plate',
    cuisineStyle: 'Syrian',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice', 'pita'],
    keyIngredients: ['chicken breast', 'garlic', 'lemon', 'yogurt', 'paprika', 'rice', 'parsley'],
  },
  {
    name: 'Chicken shawarma plate',
    cuisineStyle: 'Syrian',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice', 'pita'],
    keyIngredients: ['chicken breast', 'garlic', 'yogurt', 'paprika', 'cumin', 'rice', 'tomato'],
  },
  {
    name: 'Beef kofta with rice',
    cuisineStyle: 'Syrian',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['lean beef mince', 'parsley', 'onion', 'allspice', 'cumin', 'rice'],
  },
  {
    name: 'Freekeh with chicken',
    cuisineStyle: 'Syrian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['freekeh'],
    keyIngredients: ['chicken breast', 'freekeh', 'onion', 'cinnamon', 'allspice', 'parsley'],
  },
  {
    name: 'Mujaddara with yogurt',
    cuisineStyle: 'Syrian',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['lentils'],
    carbs: ['lentils', 'rice'],
    keyIngredients: ['lentils', 'rice', 'onion', 'cumin', 'plain yogurt'],
  },
  {
    name: 'Tuna arabi pita',
    cuisineStyle: 'Syrian',
    cookingMethod: 'raw',
    mealTypes: ['LUNCH', 'SNACK'],
    famous: true,
    proteins: ['tuna'],
    carbs: ['pita'],
    keyIngredients: ['tuna', 'pita bread', 'plain yogurt', 'parsley', 'lemon'],
  },
  {
    name: 'Labneh breakfast plate',
    cuisineStyle: 'Syrian',
    cookingMethod: 'raw',
    mealTypes: ['BREAKFAST', 'SNACK'],
    famous: true,
    proteins: ['labneh'],
    carbs: ['bread'],
    keyIngredients: ['labneh', 'tomato', 'cucumber', 'olive oil', 'zaatar', 'pita bread'],
  },
  {
    name: 'Ful medames',
    cuisineStyle: 'Syrian',
    cookingMethod: 'saute',
    mealTypes: ['BREAKFAST', 'LUNCH'],
    famous: true,
    proteins: ['chickpeas'],
    carbs: ['chickpeas', 'bread'],
    keyIngredients: ['fava beans', 'garlic', 'lemon', 'olive oil', 'parsley', 'tomato'],
  },
  {
    name: 'Chicken maqluba',
    cuisineStyle: 'Syrian',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken thigh', 'rice', 'eggplant', 'tomato', 'cinnamon', 'allspice', 'onion'],
  },
  {
    name: 'Mansaf lamb with rice',
    cuisineStyle: 'Syrian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['lamb'],
    carbs: ['rice'],
    keyIngredients: ['lamb', 'rice', 'plain yogurt', 'onion', 'cinnamon', 'parsley', 'almonds'],
  },
  {
    name: 'Syrian lentil soup',
    cuisineStyle: 'Syrian',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['lentils'],
    carbs: ['lentils'],
    keyIngredients: ['red lentils', 'onion', 'garlic', 'cumin', 'lemon', 'tomato'],
  },

  // ─── MIDDLE EASTERN ───────────────────────────────────────────────────────
  {
    name: 'Shakshuka',
    cuisineStyle: 'Middle Eastern',
    cookingMethod: 'saute',
    mealTypes: ['BREAKFAST', 'LUNCH'],
    famous: true,
    proteins: ['egg'],
    carbs: [],
    keyIngredients: ['eggs', 'tomato', 'onion', 'garlic', 'paprika', 'cumin'],
  },
  {
    name: 'Lebanese fattoush salad bowl',
    cuisineStyle: 'Middle Eastern',
    cookingMethod: 'raw',
    mealTypes: ['LUNCH', 'SNACK'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['pita'],
    keyIngredients: ['chicken breast', 'pita bread', 'tomato', 'cucumber', 'lettuce', 'sumac', 'lemon'],
  },
  {
    name: 'Moroccan chicken tagine',
    cuisineStyle: 'Middle Eastern',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['couscous'],
    keyIngredients: [
      'chicken thigh',
      'couscous',
      'onion',
      'cinnamon',
      'cumin',
      'coriander',
      'tomato',
      'preserved lemon',
    ],
  },
  {
    name: 'Egyptian koshari bowl',
    cuisineStyle: 'Middle Eastern',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['lentils'],
    carbs: ['rice', 'pasta', 'lentils'],
    keyIngredients: ['lentils', 'rice', 'pasta', 'tomato sauce', 'garlic', 'onion', 'cumin'],
  },
  {
    name: 'Spiced beef hummus bowl',
    cuisineStyle: 'Middle Eastern',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['pita'],
    keyIngredients: ['lean beef mince', 'hummus', 'pine nuts', 'paprika', 'cumin', 'pita bread'],
  },
  {
    name: 'Harira lamb lentil soup',
    cuisineStyle: 'Middle Eastern',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['lamb', 'lentils'],
    carbs: ['lentils'],
    keyIngredients: ['lamb', 'lentils', 'tomato', 'onion', 'coriander', 'cinnamon', 'ginger'],
  },
  {
    name: 'Grilled kofta pita sandwich',
    cuisineStyle: 'Middle Eastern',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['pita'],
    keyIngredients: ['lean beef mince', 'pita bread', 'parsley', 'onion', 'allspice', 'tomato', 'plain yogurt'],
  },
  {
    name: 'Lebanese chicken tawook wrap',
    cuisineStyle: 'Middle Eastern',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['pita'],
    keyIngredients: ['chicken breast', 'pita bread', 'garlic', 'lemon', 'yogurt', 'tomato', 'parsley'],
  },

  // ─── TURKISH ──────────────────────────────────────────────────────────────
  {
    name: 'Adana kebab plate',
    cuisineStyle: 'Turkish',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice', 'pita'],
    keyIngredients: ['lean beef mince', 'paprika', 'onion', 'garlic', 'cumin', 'rice', 'tomato'],
  },
  {
    name: 'Turkish chicken doner wrap',
    cuisineStyle: 'Turkish',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['wrap'],
    keyIngredients: ['chicken breast', 'tortilla wrap', 'yogurt', 'garlic', 'paprika', 'tomato', 'lettuce'],
  },
  {
    name: 'Mercimek red lentil soup',
    cuisineStyle: 'Turkish',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['lentils'],
    carbs: ['lentils'],
    keyIngredients: ['red lentils', 'onion', 'garlic', 'cumin', 'paprika', 'olive oil', 'lemon'],
  },
  {
    name: 'Turkish egg menemen',
    cuisineStyle: 'Turkish',
    cookingMethod: 'saute',
    mealTypes: ['BREAKFAST'],
    famous: true,
    proteins: ['egg'],
    carbs: [],
    keyIngredients: ['eggs', 'tomato', 'green pepper', 'onion', 'olive oil', 'paprika'],
  },
  {
    name: 'Turkish stuffed peppers biber dolmasi',
    cuisineStyle: 'Turkish',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['lean beef mince', 'bell pepper', 'rice', 'tomato', 'onion', 'parsley', 'cinnamon'],
  },
  {
    name: 'Chicken iskender plate',
    cuisineStyle: 'Turkish',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['bread'],
    keyIngredients: ['chicken breast', 'tomato sauce', 'plain yogurt', 'bread', 'paprika', 'butter'],
  },

  // ─── WESTERN ──────────────────────────────────────────────────────────────
  {
    name: 'Overnight oats',
    cuisineStyle: 'Western',
    cookingMethod: 'raw',
    mealTypes: ['BREAKFAST', 'SNACK'],
    famous: true,
    proteins: ['yogurt', 'protein powder'],
    carbs: ['oats'],
    keyIngredients: ['oats', 'greek yogurt', 'protein powder', 'berries', 'banana'],
  },
  {
    name: 'Protein pancakes',
    cuisineStyle: 'Western',
    cookingMethod: 'bake',
    mealTypes: ['BREAKFAST'],
    famous: true,
    proteins: ['egg', 'protein powder'],
    carbs: ['oats', 'banana'],
    keyIngredients: ['eggs', 'oats', 'banana', 'protein powder', 'cinnamon'],
  },
  {
    name: 'Breakfast burrito',
    cuisineStyle: 'Western',
    cookingMethod: 'saute',
    mealTypes: ['BREAKFAST'],
    famous: true,
    proteins: ['egg', 'turkey'],
    carbs: ['wrap'],
    keyIngredients: ['eggs', 'tortilla wrap', 'turkey mince', 'tomato', 'onion'],
  },
  {
    name: 'Cottage cheese fruit bowl',
    cuisineStyle: 'Western',
    cookingMethod: 'raw',
    mealTypes: ['BREAKFAST', 'SNACK'],
    famous: true,
    proteins: ['cottage cheese'],
    carbs: ['fruit'],
    keyIngredients: ['cottage cheese', 'berries', 'banana', 'chia seeds'],
  },
  {
    name: 'Protein smoothie bowl',
    cuisineStyle: 'Western',
    cookingMethod: 'raw',
    mealTypes: ['BREAKFAST', 'SNACK'],
    famous: true,
    proteins: ['protein powder', 'yogurt'],
    carbs: ['banana', 'berries'],
    keyIngredients: ['protein powder', 'banana', 'berries', 'greek yogurt', 'chia seeds'],
  },
  {
    name: 'Beef bolognese pasta',
    cuisineStyle: 'Western',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['pasta'],
    keyIngredients: ['lean beef mince', 'pasta', 'tomato sauce', 'onion', 'garlic', 'basil'],
  },
  {
    name: 'Beef burrito bowl',
    cuisineStyle: 'Western',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['lean beef mince', 'rice', 'tomato', 'avocado', 'yogurt', 'paprika'],
  },
  {
    name: 'Chicken fajita rice bowl',
    cuisineStyle: 'Western',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'bell pepper', 'onion', 'paprika', 'cumin'],
  },
  {
    name: 'Grilled sirloin steak with roasted vegetables',
    cuisineStyle: 'Western',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['steak', 'beef'],
    carbs: ['potato'],
    keyIngredients: ['sirloin steak', 'potato', 'broccoli', 'garlic', 'olive oil'],
  },
  {
    name: 'Beef stir fry with broccoli',
    cuisineStyle: 'Western',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['beef strips', 'broccoli', 'rice', 'soy sauce', 'garlic', 'ginger'],
  },
  {
    name: 'Turkey avocado brown rice bowl',
    cuisineStyle: 'Western',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['turkey'],
    carbs: ['brown rice'],
    keyIngredients: ['turkey mince', 'brown rice', 'avocado', 'tomato', 'garlic', 'lemon'],
  },
  {
    name: 'Egg white vegetable omelette',
    cuisineStyle: 'Western',
    cookingMethod: 'saute',
    mealTypes: ['BREAKFAST'],
    famous: true,
    proteins: ['egg'],
    carbs: [],
    keyIngredients: ['egg whites', 'spinach', 'bell pepper', 'onion', 'mushrooms', 'feta cheese'],
  },
  {
    name: 'Tuna stuffed sweet potato',
    cuisineStyle: 'Western',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['tuna'],
    carbs: ['sweet potato'],
    keyIngredients: ['tuna', 'sweet potato', 'plain yogurt', 'onion', 'garlic', 'lemon'],
  },
  {
    name: 'Grilled chicken salad bowl',
    cuisineStyle: 'Western',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'SNACK'],
    famous: true,
    proteins: ['chicken'],
    carbs: [],
    keyIngredients: ['chicken breast', 'lettuce', 'cucumber', 'tomato', 'olive oil', 'lemon'],
  },
  {
    name: 'Beef stuffed bell peppers',
    cuisineStyle: 'Western',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['lean beef mince', 'bell pepper', 'rice', 'tomato sauce', 'garlic', 'onion'],
  },
  {
    name: 'Turkey sweet potato bowl',
    cuisineStyle: 'Western',
    cookingMethod: 'roast',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['turkey'],
    carbs: ['sweet potato'],
    keyIngredients: ['turkey mince', 'sweet potato', 'spinach', 'garlic', 'olive oil', 'paprika'],
  },
  {
    name: 'Baked salmon with asparagus',
    cuisineStyle: 'Western',
    cookingMethod: 'roast',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['salmon'],
    carbs: ['potato'],
    keyIngredients: ['salmon fillet', 'asparagus', 'potato', 'lemon', 'garlic', 'olive oil'],
  },
  {
    name: 'Avocado egg toast',
    cuisineStyle: 'Western',
    cookingMethod: 'saute',
    mealTypes: ['BREAKFAST'],
    famous: true,
    proteins: ['egg'],
    carbs: ['bread'],
    keyIngredients: ['eggs', 'whole grain bread', 'avocado', 'tomato', 'lemon'],
  },
  {
    name: 'Chia seed pudding with berries',
    cuisineStyle: 'Western',
    cookingMethod: 'raw',
    mealTypes: ['BREAKFAST', 'SNACK'],
    famous: true,
    proteins: ['chia seeds', 'yogurt'],
    carbs: ['berries'],
    keyIngredients: ['chia seeds', 'greek yogurt', 'berries', 'banana', 'honey'],
  },

  // ─── GREEK ────────────────────────────────────────────────────────────────
  {
    name: 'Greek yogurt protein bowl',
    cuisineStyle: 'Greek',
    cookingMethod: 'raw',
    mealTypes: ['BREAKFAST', 'SNACK'],
    famous: true,
    proteins: ['yogurt'],
    carbs: ['oats', 'fruit'],
    keyIngredients: ['greek yogurt', 'oats', 'berries', 'banana', 'chia seeds'],
  },
  {
    name: 'Chicken souvlaki bowl',
    cuisineStyle: 'Greek',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice', 'potato'],
    keyIngredients: ['chicken breast', 'lemon', 'garlic', 'oregano', 'rice', 'cucumber', 'greek yogurt'],
  },
  {
    name: 'Greek lemon roasted chicken',
    cuisineStyle: 'Greek',
    cookingMethod: 'roast',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['potato'],
    keyIngredients: ['chicken breast', 'potato', 'lemon', 'garlic', 'oregano', 'olive oil'],
  },
  {
    name: 'Greek baked moussaka',
    cuisineStyle: 'Greek',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['eggplant'],
    keyIngredients: ['lean beef mince', 'eggplant', 'tomato sauce', 'onion', 'cinnamon', 'plain yogurt'],
  },
  {
    name: 'Greek chicken pita wrap',
    cuisineStyle: 'Greek',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['pita'],
    keyIngredients: ['chicken breast', 'pita bread', 'lettuce', 'tomato', 'cucumber', 'plain yogurt', 'oregano'],
  },
  {
    name: 'Fasolia white bean stew',
    cuisineStyle: 'Greek',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken', 'beans'],
    carbs: ['white beans'],
    keyIngredients: ['white beans', 'chicken breast', 'tomato', 'onion', 'garlic', 'olive oil', 'parsley'],
  },

  // ─── MEDITERRANEAN ────────────────────────────────────────────────────────
  {
    name: 'Turkey meatballs with tomato pasta',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['turkey'],
    carbs: ['pasta'],
    keyIngredients: ['turkey mince', 'pasta', 'tomato sauce', 'garlic', 'basil'],
  },
  {
    name: 'Pan-seared salmon with roasted vegetables',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'roast',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['salmon'],
    carbs: ['potato'],
    keyIngredients: ['salmon fillet', 'potato', 'zucchini', 'tomato', 'olive oil', 'lemon'],
  },
  {
    name: 'Salmon with quinoa and greens',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'roast',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['salmon'],
    carbs: ['quinoa'],
    keyIngredients: ['salmon fillet', 'quinoa', 'spinach', 'lemon', 'olive oil'],
  },
  {
    name: 'Tuna pasta salad',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'raw',
    mealTypes: ['LUNCH', 'SNACK'],
    famous: true,
    proteins: ['tuna'],
    carbs: ['pasta'],
    keyIngredients: ['tuna', 'pasta', 'cucumber', 'tomato', 'plain yogurt', 'lemon'],
  },
  {
    name: 'Tuna nicoise salad bowl',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'raw',
    mealTypes: ['LUNCH'],
    famous: true,
    proteins: ['tuna'],
    carbs: ['potato'],
    keyIngredients: ['tuna', 'eggs', 'green beans', 'potato', 'tomato', 'olive oil', 'lemon'],
  },
  {
    name: 'Baked cod with tomatoes and olives',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['cod'],
    carbs: ['potato'],
    keyIngredients: ['cod fillet', 'tomato', 'olives', 'garlic', 'olive oil', 'potato', 'lemon'],
  },
  {
    name: 'Spanish chicken with rice',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'onion', 'garlic', 'tomato', 'paprika', 'cumin'],
  },
  {
    name: 'Grilled sea bass with lemon herbs',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['fish'],
    carbs: ['potato'],
    keyIngredients: ['sea bass fillet', 'lemon', 'garlic', 'olive oil', 'parsley', 'potato'],
  },
  {
    name: 'Turkish stuffed zucchini with beef',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['lean beef mince', 'zucchini', 'rice', 'tomato sauce', 'onion', 'cinnamon'],
  },
  {
    name: 'Mediterranean chicken bulgur bowl',
    cuisineStyle: 'Mediterranean',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['bulgur'],
    keyIngredients: ['chicken breast', 'bulgur', 'tomato', 'cucumber', 'parsley', 'lemon', 'olive oil'],
  },

  // ─── ITALIAN ──────────────────────────────────────────────────────────────
  {
    name: 'Turkey meatball marinara',
    cuisineStyle: 'Italian',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['turkey'],
    carbs: ['pasta'],
    keyIngredients: ['turkey mince', 'pasta', 'tomato sauce', 'garlic', 'basil'],
  },
  {
    name: 'Caprese chicken pasta',
    cuisineStyle: 'Italian',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['pasta'],
    keyIngredients: ['chicken breast', 'pasta', 'tomato', 'basil', 'mozzarella'],
  },
  {
    name: 'Chicken piccata with pasta',
    cuisineStyle: 'Italian',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['pasta'],
    keyIngredients: ['chicken breast', 'pasta', 'lemon', 'garlic', 'capers', 'parsley', 'olive oil'],
  },
  {
    name: 'Penne arrabbiata with chicken',
    cuisineStyle: 'Italian',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['pasta'],
    keyIngredients: ['chicken breast', 'penne pasta', 'tomato sauce', 'garlic', 'chili flakes', 'parsley'],
  },
  {
    name: 'Chicken cacciatore',
    cuisineStyle: 'Italian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['potato'],
    keyIngredients: ['chicken thigh', 'tomato sauce', 'bell pepper', 'onion', 'garlic', 'oregano', 'potato'],
  },
  {
    name: 'Minestrone chicken soup',
    cuisineStyle: 'Italian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['pasta', 'beans'],
    keyIngredients: ['chicken breast', 'pasta', 'white beans', 'tomato', 'carrot', 'onion', 'garlic', 'basil'],
  },
  {
    name: 'Italian turkey meatloaf',
    cuisineStyle: 'Italian',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['turkey'],
    carbs: ['bread'],
    keyIngredients: ['turkey mince', 'tomato sauce', 'onion', 'garlic', 'parsley', 'egg', 'bread'],
  },
  {
    name: 'Chicken gnocchi soup',
    cuisineStyle: 'Italian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['gnocchi'],
    keyIngredients: ['chicken breast', 'gnocchi', 'spinach', 'onion', 'garlic', 'tomato', 'basil'],
  },

  // ─── MEXICAN ──────────────────────────────────────────────────────────────
  {
    name: 'Chicken fajita wrap',
    cuisineStyle: 'Mexican',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['wrap'],
    keyIngredients: ['chicken breast', 'tortilla wrap', 'bell pepper', 'onion', 'paprika', 'tomato'],
  },
  {
    name: 'Beef taco bowl',
    cuisineStyle: 'Mexican',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['lean beef mince', 'rice', 'tomato', 'onion', 'avocado', 'paprika'],
  },
  {
    name: 'Chicken burrito bowl',
    cuisineStyle: 'Mexican',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'black beans', 'tomato', 'onion', 'paprika', 'cumin'],
  },
  {
    name: 'Turkey enchilada bowl',
    cuisineStyle: 'Mexican',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['turkey'],
    carbs: ['wrap'],
    keyIngredients: ['turkey mince', 'tomato sauce', 'tortilla wrap', 'onion', 'garlic', 'paprika', 'cumin'],
  },
  {
    name: 'Chicken tortilla soup',
    cuisineStyle: 'Mexican',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['tortilla'],
    keyIngredients: ['chicken breast', 'tomato', 'onion', 'garlic', 'cumin', 'tortilla wrap', 'avocado'],
  },
  {
    name: 'Mexican beef rice bowl',
    cuisineStyle: 'Mexican',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['beef strips', 'rice', 'bell pepper', 'onion', 'garlic', 'paprika', 'cumin', 'lime juice'],
  },

  // ─── ASIAN (General / Chinese-influenced) ─────────────────────────────────
  {
    name: 'Chicken teriyaki rice bowl',
    cuisineStyle: 'Asian',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'soy sauce', 'garlic', 'ginger', 'broccoli'],
  },
  {
    name: 'Beef and broccoli stir fry',
    cuisineStyle: 'Asian',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['beef strips', 'broccoli', 'rice', 'soy sauce', 'garlic', 'ginger'],
  },
  {
    name: 'Vietnamese chicken pho',
    cuisineStyle: 'Asian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice noodles'],
    keyIngredients: ['chicken breast', 'rice noodles', 'onion', 'ginger', 'star anise', 'cinnamon', 'bean sprouts'],
  },
  {
    name: 'Pad see ew noodles with chicken',
    cuisineStyle: 'Asian',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice noodles'],
    keyIngredients: ['chicken breast', 'rice noodles', 'broccoli', 'soy sauce', 'garlic', 'egg'],
  },
  {
    name: 'Hainanese chicken rice',
    cuisineStyle: 'Asian',
    cookingMethod: 'steam',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'ginger', 'garlic', 'sesame oil', 'cucumber'],
  },
  {
    name: 'Chinese kung pao chicken',
    cuisineStyle: 'Asian',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'peanuts', 'soy sauce', 'garlic', 'ginger', 'chili flakes'],
  },
  {
    name: 'Asian beef fried rice',
    cuisineStyle: 'Asian',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['beef strips', 'rice', 'egg', 'soy sauce', 'garlic', 'ginger', 'onion', 'carrot'],
  },
  {
    name: 'Glass noodle beef salad',
    cuisineStyle: 'Asian',
    cookingMethod: 'raw',
    mealTypes: ['LUNCH'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice noodles'],
    keyIngredients: ['beef', 'glass noodles', 'cucumber', 'garlic', 'lemon juice', 'chili flakes', 'coriander'],
  },

  // ─── JAPANESE ─────────────────────────────────────────────────────────────
  {
    name: 'Chicken ramen bowl',
    cuisineStyle: 'Japanese',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['noodles'],
    keyIngredients: ['chicken breast', 'ramen noodles', 'egg', 'soy sauce', 'ginger', 'garlic', 'spinach'],
  },
  {
    name: 'Teriyaki salmon donburi',
    cuisineStyle: 'Japanese',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['salmon'],
    carbs: ['rice'],
    keyIngredients: ['salmon fillet', 'rice', 'soy sauce', 'garlic', 'sesame oil', 'cucumber', 'avocado'],
  },
  {
    name: 'Japanese chicken katsu curry',
    cuisineStyle: 'Japanese',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'onion', 'carrot', 'garlic', 'ginger', 'soy sauce', 'cumin'],
  },
  {
    name: 'Gyudon beef rice bowl',
    cuisineStyle: 'Japanese',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['beef strips', 'rice', 'onion', 'soy sauce', 'ginger', 'egg'],
  },
  {
    name: 'Miso salmon with edamame rice',
    cuisineStyle: 'Japanese',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['salmon'],
    carbs: ['rice'],
    keyIngredients: ['salmon fillet', 'rice', 'edamame', 'soy sauce', 'sesame oil', 'ginger'],
  },
  {
    name: 'Chicken yakitori skewers',
    cuisineStyle: 'Japanese',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER', 'SNACK'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'soy sauce', 'garlic', 'sesame oil', 'spring onion'],
  },
  {
    name: 'Salmon sushi bowl',
    cuisineStyle: 'Japanese',
    cookingMethod: 'raw',
    mealTypes: ['LUNCH'],
    famous: true,
    proteins: ['salmon'],
    carbs: ['rice'],
    keyIngredients: ['salmon fillet', 'rice', 'avocado', 'cucumber', 'soy sauce', 'sesame oil', 'sesame seeds'],
  },
  {
    name: 'Japanese tamago egg rice bowl',
    cuisineStyle: 'Japanese',
    cookingMethod: 'saute',
    mealTypes: ['BREAKFAST'],
    famous: true,
    proteins: ['egg'],
    carbs: ['rice'],
    keyIngredients: ['eggs', 'rice', 'soy sauce', 'sesame oil', 'spring onion', 'ginger'],
  },

  // ─── KOREAN ───────────────────────────────────────────────────────────────
  {
    name: 'Bibimbap with beef',
    cuisineStyle: 'Korean',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['beef strips', 'rice', 'spinach', 'carrot', 'egg', 'soy sauce', 'sesame oil', 'garlic'],
  },
  {
    name: 'Korean bulgogi beef bowl',
    cuisineStyle: 'Korean',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['beef strips', 'rice', 'soy sauce', 'garlic', 'ginger', 'sesame oil', 'onion'],
  },
  {
    name: 'Dakgalbi spicy chicken stir-fry',
    cuisineStyle: 'Korean',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'cabbage', 'garlic', 'ginger', 'soy sauce', 'paprika', 'onion'],
  },
  {
    name: 'Korean sesame chicken rice bowl',
    cuisineStyle: 'Korean',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: [
      'chicken breast',
      'rice',
      'soy sauce',
      'sesame oil',
      'garlic',
      'ginger',
      'spring onion',
      'broccoli',
    ],
  },
  {
    name: 'Japchae noodles with beef',
    cuisineStyle: 'Korean',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['beef'],
    carbs: ['noodles'],
    keyIngredients: ['beef strips', 'glass noodles', 'spinach', 'carrot', 'soy sauce', 'sesame oil', 'garlic'],
  },
  {
    name: 'Korean chicken jjigae stew',
    cuisineStyle: 'Korean',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'tofu', 'garlic', 'ginger', 'soy sauce', 'onion', 'rice'],
  },
  {
    name: 'Kimchi fried rice with chicken',
    cuisineStyle: 'Korean',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'kimchi', 'egg', 'soy sauce', 'sesame oil', 'garlic'],
  },
  {
    name: 'Korean egg rice porridge',
    cuisineStyle: 'Korean',
    cookingMethod: 'braise',
    mealTypes: ['BREAKFAST'],
    famous: true,
    proteins: ['egg'],
    carbs: ['rice'],
    keyIngredients: ['rice', 'eggs', 'sesame oil', 'garlic', 'spring onion', 'soy sauce'],
  },

  // ─── THAI ─────────────────────────────────────────────────────────────────
  {
    name: 'Thai basil chicken stir-fry',
    cuisineStyle: 'Thai',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken mince', 'rice', 'basil', 'garlic', 'soy sauce', 'fish sauce', 'chili flakes'],
  },
  {
    name: 'Thai green curry chicken',
    cuisineStyle: 'Thai',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'curry paste', 'garlic', 'ginger', 'spinach', 'lemongrass'],
  },
  {
    name: 'Pad thai with chicken',
    cuisineStyle: 'Thai',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice noodles'],
    keyIngredients: ['chicken breast', 'rice noodles', 'egg', 'fish sauce', 'garlic', 'onion', 'bean sprouts'],
  },
  {
    name: 'Thai larb beef salad',
    cuisineStyle: 'Thai',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH'],
    famous: true,
    proteins: ['beef'],
    carbs: ['rice'],
    keyIngredients: ['beef mince', 'rice', 'onion', 'lime juice', 'fish sauce', 'chili flakes', 'mint', 'coriander'],
  },
  {
    name: 'Tom kha chicken soup',
    cuisineStyle: 'Thai',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'mushrooms', 'ginger', 'lemongrass', 'garlic', 'lime juice', 'rice'],
  },
  {
    name: 'Thai massaman chicken',
    cuisineStyle: 'Thai',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['potato', 'rice'],
    keyIngredients: [
      'chicken breast',
      'potato',
      'onion',
      'garlic',
      'cinnamon',
      'cumin',
      'coconut milk alternative',
      'rice',
    ],
  },
  {
    name: 'Thai pineapple chicken fried rice',
    cuisineStyle: 'Thai',
    cookingMethod: 'stir-fry',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'rice', 'pineapple', 'egg', 'soy sauce', 'garlic', 'ginger', 'cashews'],
  },

  // ─── INDIAN ───────────────────────────────────────────────────────────────
  {
    name: 'Chicken tikka masala bowl',
    cuisineStyle: 'Indian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'tomato', 'garlic', 'ginger', 'plain yogurt', 'rice', 'cumin', 'coriander'],
  },
  {
    name: 'Chana masala with rice',
    cuisineStyle: 'Indian',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chickpeas'],
    carbs: ['rice', 'chickpeas'],
    keyIngredients: ['chickpeas', 'tomato', 'onion', 'garlic', 'ginger', 'rice', 'cumin', 'turmeric'],
  },
  {
    name: 'Palak chicken',
    cuisineStyle: 'Indian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'spinach', 'tomato', 'onion', 'garlic', 'ginger', 'rice', 'cumin'],
  },
  {
    name: 'Tandoori chicken with raita',
    cuisineStyle: 'Indian',
    cookingMethod: 'grill',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'plain yogurt', 'garlic', 'ginger', 'paprika', 'cumin', 'turmeric', 'rice'],
  },
  {
    name: 'Dal makhani with rice',
    cuisineStyle: 'Indian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['lentils'],
    carbs: ['rice', 'lentils'],
    keyIngredients: ['lentils', 'tomato', 'onion', 'garlic', 'ginger', 'rice', 'cumin', 'turmeric', 'coriander'],
  },
  {
    name: 'Butter chicken with rice',
    cuisineStyle: 'Indian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: ['chicken breast', 'tomato sauce', 'plain yogurt', 'garlic', 'ginger', 'rice', 'cumin', 'turmeric'],
  },
  {
    name: 'Chicken biryani',
    cuisineStyle: 'Indian',
    cookingMethod: 'bake',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['rice'],
    keyIngredients: [
      'chicken breast',
      'rice',
      'onion',
      'garlic',
      'ginger',
      'plain yogurt',
      'cinnamon',
      'cumin',
      'turmeric',
    ],
  },
  {
    name: 'Rajma kidney bean curry',
    cuisineStyle: 'Indian',
    cookingMethod: 'braise',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['kidney beans'],
    carbs: ['rice', 'kidney beans'],
    keyIngredients: ['kidney beans', 'tomato', 'onion', 'garlic', 'ginger', 'rice', 'cumin', 'turmeric'],
  },
  {
    name: 'Indian masala egg scramble',
    cuisineStyle: 'Indian',
    cookingMethod: 'saute',
    mealTypes: ['BREAKFAST'],
    famous: true,
    proteins: ['egg'],
    carbs: ['bread'],
    keyIngredients: ['eggs', 'tomato', 'onion', 'garlic', 'ginger', 'cumin', 'turmeric', 'coriander'],
  },
  {
    name: 'Chicken keema with naan',
    cuisineStyle: 'Indian',
    cookingMethod: 'saute',
    mealTypes: ['LUNCH', 'DINNER'],
    famous: true,
    proteins: ['chicken'],
    carbs: ['bread'],
    keyIngredients: ['chicken mince', 'peas', 'tomato', 'onion', 'garlic', 'ginger', 'cumin', 'turmeric'],
  },
];
