'use client';

import { useMemo } from 'react';
import type { RapidAPIFilterOptions } from '@/features/exercises/types/rapidapi-filters.types';

/**
 * Hook to get available filter options for RapidAPI ExerciseDB
 * Returns predefined body parts, equipments, and target muscles
 */
export function useRapidAPIFilterOptions(): RapidAPIFilterOptions {
  return useMemo(
    () => ({
      bodyParts: [
        'BACK',
        'CARDIO',
        'CHEST',
        'FOREARMS',
        'GLUTES',
        'HAMSTRINGS',
        'LATS',
        'LOWER BACK',
        'LOWER LEGS',
        'NECK',
        'SHOULDERS',
        'THIGHS',
        'TRAPS',
        'TRICEPS',
        'UPPER BACK',
        'UPPER LEGS',
        'WAIST',
      ],
      equipments: [
        'ASSISTED',
        'BAND',
        'BARBELL',
        'CABLE',
        'DUMBBELL',
        'ELLIPTICAL MACHINE',
        'EZ BARBELL',
        'FOAM ROLL',
        'KETTLEBELL',
        'LEVERAGE MACHINE',
        'MEDICINE BALL',
        'OLYMPIC BARBELL',
        'RESISTANCE BAND',
        'ROLLER',
        'ROPE',
        'ROWING MACHINE',
        'SLED MACHINE',
        'SMITH MACHINE',
        'STABILITY BALL',
        'STATIONARY BIKE',
        'STEPMILL MACHINE',
        'TIRE',
        'TREADMILL',
        'TRAP BAR',
        'UPPER BODY ERGOMETER',
        'WEIGHTED',
        'WHEEL ROLLER',
      ],
      targetMuscles: [
        'ABDOMINALS',
        'ADDUCTORS',
        'ANTERIOR DELTOID',
        'BICEPS',
        'BRACHIALIS',
        'BRACHIORADIALIS',
        'EXTENSOR CARPI RADIALIS',
        'EXTENSOR CARPI RADIALIS LONGUS',
        'EXTENSOR CARPI ULNARIS',
        'EXTENSOR DIGITORUM',
        'EXTENSOR POLLICIS LONGUS',
        'EXTRINSIC HAND MUSCLES',
        'FLEXOR CARPI RADIALIS',
        'FLEXOR CARPI RADIALIS LONGUS',
        'FLEXOR CARPI ULNARIS',
        'FLEXOR DIGITORUM',
        'FLEXOR POLLICIS LONGUS',
        'GASTROCNEMIUS',
        'GEMELLUS INFERIOR',
        'GEMELLUS SUPERIOR',
        'GLUTEUS MAXIMUS',
        'GLUTEUS MEDIUS',
        'GLUTEUS MINIMUS',
        'GRACILIS',
        'ILIOPSOAS',
        'ILIACUS',
        'INFRASPINATUS',
        'INTEROSSEI',
        'INTRINSIC HAND MUSCLES',
        'LATISSIMUS DORSI',
        'LEVATOR SCAPULAE',
        'LEVATORES COSTARUM',
        'LONGISSIMUS',
        'LONGUS CAPITIS',
        'LONGUS COLLI',
        'LOWER TRAPEZIUS',
        'LUMBRICALS',
        'MIDDLE TRAPEZIUS',
        'MULTIFIDUS',
        'OBTURATOR EXTERNUS',
        'OBTURATOR INTERNUS',
        'OCCIPITALIS',
        'PALMARIS BREVIS',
        'PALMARIS LONGUS',
        'PECTINEUS',
        'PECTORALIS MAJOR',
        'PECTORALIS MINOR',
        'PERONEUS',
        'PERONEUS BREVIS',
        'PERONEUS LONGUS',
        'PLANTARIS',
        'PLATYSMA',
        'POSTERIOR DELTOID',
        'PRONATOR QUADRATUS',
        'PRONATOR TERES',
        'PSOAS MAJOR',
        'PSOAS MINOR',
        'QUADRATUS FEMORIS',
        'QUADRATUS LUMBORUM',
        'QUADRICEPS',
        'RECTUS FEMORIS',
        'RHOMBOID MAJOR',
        'RHOMBOID MINOR',
        'RISORIUS',
        'SARTORIUS',
        'SCALENES',
        'SCALENUS ANTERIOR',
        'SCALENUS MEDIUS',
        'SCALENUS POSTERIOR',
        'SEMIMEMBRANOSUS',
        'SEMITENDINOSUS',
        'SERRATUS ANTERIOR',
        'SOLEUS',
        'SPLENIUS',
        'SPLENIUS CAPITIS',
        'SPLENIUS CERVICIS',
        'STERNOCLEIDOMASTOID',
        'SUBCLAVIUS',
        'SUBSCAPULARIS',
        'SUPINATOR',
        'SUPRASPINATUS',
        'TIBIALIS ANTERIOR',
        'TIBIALIS POSTERIOR',
        'TRANSVERSE ABDOMINIS',
        'TRANSVEROSPINALIS',
        'TRAPEZIUS',
        'TRICEPS',
        'UPPER TRAPEZIUS',
        'VASTUS INTERMEDIUS',
        'VASTUS LATERALIS',
        'VASTUS MEDIALIS',
      ],
      difficulties: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'],
    }),
    [],
  );
}
