import { prisma } from '@/lib/prisma'; // adjust path to your prisma singleton file
import { Prisma, DifficultyLevel, VideoCategory } from '@prisma/client';

const sampleVideos: Prisma.VideoCreateInput[] = [
  // STRENGTH TRAINING
  {
    title: 'Barbell Squat',
    description: 'Build leg strength and power with proper squat form',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=ecorNlGUO8E',
    thumbnailUrl: 'https://example.com/barbell-squat.jpg',
    equipment: JSON.stringify(['Barbell', 'Rack']),
    muscleGroups: JSON.stringify(['Quadriceps', 'Glutes', 'Core']),
    tags: JSON.stringify(['strength', 'legs', 'compound']),
    instructions: JSON.stringify([
      'Place bar on upper back',
      'Feet shoulder-width apart',
      'Descend until thighs parallel',
      'Drive through heels to stand',
    ]),
    tips: JSON.stringify(['Keep chest up', 'Knees track toes', 'Full depth for strength gains']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Deadlift',
    description: 'Master the deadlift for total body strength',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSmeVQ',
    thumbnailUrl: 'https://example.com/deadlift.jpg',
    equipment: JSON.stringify(['Barbell']),
    muscleGroups: JSON.stringify(['Back', 'Hamstrings', 'Glutes', 'Core']),
    tags: JSON.stringify(['strength', 'compound', 'back']),
    instructions: JSON.stringify([
      'Bar over mid-foot',
      'Grip shoulder-width',
      'Engage lats and core',
      'Drive through heels',
    ]),
    tips: JSON.stringify(['Keep bar close to body', 'Neutral spine', 'Hinge at hips']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Bench Press',
    description: 'Build chest, shoulders, and triceps',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    thumbnailUrl: 'https://example.com/bench-press.jpg',
    equipment: JSON.stringify(['Barbell', 'Bench']),
    muscleGroups: JSON.stringify(['Chest', 'Shoulders', 'Triceps']),
    tags: JSON.stringify(['strength', 'chest', 'compound']),
    instructions: JSON.stringify([
      'Lie flat on bench',
      'Grip slightly wider than shoulders',
      'Lower bar to chest',
      'Press bar back up',
    ]),
    tips: JSON.stringify(['Full range of motion', 'Scapula retraction', 'Steady tempo']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Dumbbell Row',
    description: 'Strengthen back with single-arm rows',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=xl6Tm-e2_VM',
    thumbnailUrl: 'https://example.com/dumbbell-row.jpg',
    equipment: JSON.stringify(['Dumbbell', 'Bench']),
    muscleGroups: JSON.stringify(['Back', 'Biceps']),
    tags: JSON.stringify(['strength', 'back', 'unilateral']),
    instructions: JSON.stringify([
      'Place one knee on bench',
      'Row dumbbell to hip',
      'Squeeze back at top',
      'Control descent',
    ]),
    tips: JSON.stringify(['Retract scapula', 'Full range', 'Same reps each side']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Overhead Press',
    description: 'Build shoulder strength and stability',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=CnBmE4XwKqY',
    thumbnailUrl: 'https://example.com/overhead-press.jpg',
    equipment: JSON.stringify(['Barbell']),
    muscleGroups: JSON.stringify(['Shoulders', 'Triceps', 'Core']),
    tags: JSON.stringify(['strength', 'shoulders', 'compound']),
    instructions: JSON.stringify([
      'Rack bar at shoulder height',
      'Feet shoulder-width apart',
      'Press overhead',
      'Lock out at top',
    ]),
    tips: JSON.stringify(['Engage core', 'Neutral grip', 'Full lockout']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Pull-ups',
    description: 'Master your body weight for upper back strength',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=eYuYDrXl8Zw',
    thumbnailUrl: 'https://example.com/pull-ups.jpg',
    equipment: JSON.stringify(['Pull-up Bar']),
    muscleGroups: JSON.stringify(['Back', 'Biceps', 'Core']),
    tags: JSON.stringify(['strength', 'back', 'bodyweight']),
    instructions: JSON.stringify([
      'Grip slightly wider than shoulders',
      'Pull chin above bar',
      'Lower with control',
      'Avoid swinging',
    ]),
    tips: JSON.stringify(['Scapular engagement', 'Full range', 'Chin over bar']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Dumbbell Curl',
    description: 'Isolate biceps for arm development',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    thumbnailUrl: 'https://example.com/dumbbell-curl.jpg',
    equipment: JSON.stringify(['Dumbbells']),
    muscleGroups: JSON.stringify(['Biceps']),
    tags: JSON.stringify(['strength', 'arms', 'isolation']),
    instructions: JSON.stringify([
      'Stand with dumbbells at sides',
      'Curl weights to shoulders',
      'Squeeze at top',
      'Lower with control',
    ]),
    tips: JSON.stringify(['Avoid momentum', 'Full range', 'Strict form']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Tricep Dips',
    description: 'Build tricep strength with bodyweight',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=6kALZisCUOU',
    thumbnailUrl: 'https://example.com/tricep-dips.jpg',
    equipment: JSON.stringify(['Dip Station']),
    muscleGroups: JSON.stringify(['Triceps', 'Chest', 'Shoulders']),
    tags: JSON.stringify(['strength', 'arms', 'bodyweight']),
    instructions: JSON.stringify([
      'Grip dip station',
      'Lower body until 90 degrees',
      'Press back up',
      'Full range of motion',
    ]),
    tips: JSON.stringify(['Lean forward slightly', 'Control descent', 'Full dip']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Leg Press',
    description: 'Build leg strength safely on the leg press machine',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=IZxyjW7MIAI',
    thumbnailUrl: 'https://example.com/leg-press.jpg',
    equipment: JSON.stringify(['Leg Press Machine']),
    muscleGroups: JSON.stringify(['Quadriceps', 'Glutes', 'Hamstrings']),
    tags: JSON.stringify(['strength', 'legs', 'machine']),
    instructions: JSON.stringify([
      'Sit with back against pad',
      'Feet shoulder-width apart',
      'Lower weight to 90 degrees',
      'Press back up',
    ]),
    tips: JSON.stringify(['Full range', 'Knees aligned', 'Controlled motion']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Lat Pulldown',
    description: 'Target your lats for wider back development',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=CAwPI5NcqqM',
    thumbnailUrl: 'https://example.com/lat-pulldown.jpg',
    equipment: JSON.stringify(['Cable Machine']),
    muscleGroups: JSON.stringify(['Back', 'Biceps']),
    tags: JSON.stringify(['strength', 'back', 'machine']),
    instructions: JSON.stringify(['Sit upright', 'Grip wider than shoulders', 'Pull bar to chest', 'Control ascent']),
    tips: JSON.stringify(['Lean back slightly', 'Scapular retraction', 'Full range']),
    coach: { connect: { id: '' } },
  },

  // CARDIO
  {
    title: 'HIIT Cardio Blast',
    description: 'High-intensity interval training for maximum fat burn',
    category: VideoCategory.CARDIO,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 1800,
    videoUrl: 'https://www.youtube.com/watch?v=Nz6jLGICRgE',
    thumbnailUrl: 'https://example.com/thumb2.jpg',
    equipment: JSON.stringify(['None']),
    muscleGroups: JSON.stringify(['Full Body', 'Cardiovascular']),
    tags: JSON.stringify(['cardio', 'hiit', 'fat-burn']),
    instructions: JSON.stringify([
      'Warm up for 5 minutes',
      '30 seconds work, 15 seconds rest',
      'Repeat for 8 rounds',
      'Cool down for 5 minutes',
    ]),
    tips: JSON.stringify(['Push yourself during work intervals', 'Use rest periods to recover', 'Stay hydrated']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Steady-State Treadmill',
    description: 'Build aerobic capacity with consistent cardio',
    category: VideoCategory.CARDIO,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 2400,
    videoUrl: 'https://www.youtube.com/watch?v=loZXw7aX9MQ',
    thumbnailUrl: 'https://example.com/treadmill.jpg',
    equipment: JSON.stringify(['Treadmill']),
    muscleGroups: JSON.stringify(['Cardiovascular', 'Legs']),
    tags: JSON.stringify(['cardio', 'steady-state', 'beginner']),
    instructions: JSON.stringify([
      'Set treadmill to desired speed',
      'Maintain consistent pace',
      'Focus on breathing',
      'Cool down gradually',
    ]),
    tips: JSON.stringify(['Comfortable pace', 'Good posture', 'Regular sessions']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Jump Rope',
    description: 'Classic cardio for coordination and endurance',
    category: VideoCategory.CARDIO,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 900,
    videoUrl: 'https://www.youtube.com/watch?v=6Z4Jkf_5IvQ',
    thumbnailUrl: 'https://example.com/jump-rope.jpg',
    equipment: JSON.stringify(['Jump Rope']),
    muscleGroups: JSON.stringify(['Cardiovascular', 'Calves', 'Shoulders']),
    tags: JSON.stringify(['cardio', 'coordination', 'equipment']),
    instructions: JSON.stringify([
      'Hold rope at waist height',
      'Jump with rhythm',
      'Land on balls of feet',
      'Maintain steady tempo',
    ]),
    tips: JSON.stringify(['Wrist rotation', 'Light footsteps', 'Increase duration gradually']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Cycling Intervals',
    description: 'Build power and endurance on the bike',
    category: VideoCategory.CARDIO,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 1800,
    videoUrl: 'https://www.youtube.com/watch?v=p8oCJoIsHkQ',
    thumbnailUrl: 'https://example.com/cycling.jpg',
    equipment: JSON.stringify(['Stationary Bike']),
    muscleGroups: JSON.stringify(['Cardiovascular', 'Legs']),
    tags: JSON.stringify(['cardio', 'intervals', 'legs']),
    instructions: JSON.stringify([
      'Warm up 3 minutes',
      'High intensity 30 seconds',
      'Recovery 90 seconds',
      'Repeat 6-8 times',
    ]),
    tips: JSON.stringify(['Adjust resistance appropriately', 'Maintain form', 'Stay hydrated']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Rowing Machine',
    description: 'Full-body cardio and strength with rowing',
    category: VideoCategory.CARDIO,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 1800,
    videoUrl: 'https://www.youtube.com/watch?v=oP6OR3ahAXk',
    thumbnailUrl: 'https://example.com/rowing.jpg',
    equipment: JSON.stringify(['Rowing Machine']),
    muscleGroups: JSON.stringify(['Back', 'Legs', 'Cardiovascular', 'Core']),
    tags: JSON.stringify(['cardio', 'strength', 'full-body']),
    instructions: JSON.stringify([
      'Sit with knees bent',
      'Drive through legs first',
      'Row handle to chest',
      'Extend arms and lean forward',
    ]),
    tips: JSON.stringify(['Proper sequencing', 'Smooth strokes', 'Full range']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Sprint Intervals',
    description: 'Short, intense efforts for maximum intensity',
    category: VideoCategory.CARDIO,
    difficulty: DifficultyLevel.ADVANCED,
    duration: 900,
    videoUrl: 'https://www.youtube.com/watch?v=vn4-q7kTJY4',
    thumbnailUrl: 'https://example.com/sprints.jpg',
    equipment: JSON.stringify(['None']),
    muscleGroups: JSON.stringify(['Cardiovascular', 'Legs']),
    tags: JSON.stringify(['cardio', 'sprints', 'advanced']),
    instructions: JSON.stringify([
      'Warm up 5 minutes',
      'All-out sprint 20 seconds',
      'Rest 2 minutes',
      'Repeat 6 times',
    ]),
    tips: JSON.stringify(['All-out effort', 'Full recovery', 'Surface matters']),
    coach: { connect: { id: '' } },
  },

  // YOGA & MOBILITY
  {
    title: 'Morning Yoga Flow',
    description: 'A gentle 20-minute yoga flow perfect for starting your day',
    category: VideoCategory.YOGA,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 1200,
    videoUrl: 'https://www.youtube.com/watch?v=v7AYKMP6rOE',
    thumbnailUrl: 'https://example.com/thumb1.jpg',
    equipment: JSON.stringify(['Yoga Mat']),
    muscleGroups: JSON.stringify(['Full Body', 'Core']),
    tags: JSON.stringify(['morning', 'flexibility', 'beginner']),
    instructions: JSON.stringify([
      "Start in child's pose",
      'Move through cat-cow stretches',
      'Flow through sun salutations',
      'End in savasana',
    ]),
    tips: JSON.stringify(['Listen to your body', 'Focus on breathing', 'Modify poses as needed']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Vinyasa Flow',
    description: 'Dynamic yoga linking breath with movement',
    category: VideoCategory.YOGA,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 1500,
    videoUrl: 'https://www.youtube.com/watch?v=agFjPn1TvHE',
    thumbnailUrl: 'https://example.com/vinyasa.jpg',
    equipment: JSON.stringify(['Yoga Mat']),
    muscleGroups: JSON.stringify(['Full Body', 'Strength', 'Flexibility']),
    tags: JSON.stringify(['yoga', 'flow', 'strength']),
    instructions: JSON.stringify([
      'Synchronize breath and movement',
      'Flow through poses smoothly',
      'Maintain connection',
      'Move mindfully',
    ]),
    tips: JSON.stringify(['Breath first', 'Safe transitions', 'Listen to body']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Post-Workout Stretch',
    description: 'Essential stretches to cool down after your workout',
    category: VideoCategory.MOBILITY,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 900,
    videoUrl: 'https://www.youtube.com/watch?v=g_tea8ZNk5A',
    thumbnailUrl: 'https://example.com/thumb4.jpg',
    equipment: JSON.stringify(['Yoga Mat']),
    muscleGroups: JSON.stringify(['Full Body']),
    tags: JSON.stringify(['cooldown', 'stretching', 'recovery']),
    instructions: JSON.stringify([
      'Hold each stretch for 30 seconds',
      'Breathe deeply',
      "Don't bounce",
      'Focus on tight areas',
    ]),
    tips: JSON.stringify(['Stretch when muscles are warm', 'Never stretch to pain', 'Consistency is key']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Foam Rolling',
    description: 'Self-myofascial release for recovery',
    category: VideoCategory.MOBILITY,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 1200,
    videoUrl: 'https://www.youtube.com/watch?v=q_u1cMGZSNE',
    thumbnailUrl: 'https://example.com/foam-rolling.jpg',
    equipment: JSON.stringify(['Foam Roller']),
    muscleGroups: JSON.stringify(['Full Body']),
    tags: JSON.stringify(['recovery', 'mobility', 'self-care']),
    instructions: JSON.stringify([
      'Target each muscle group',
      'Slow rolls over tight areas',
      'Breathe through soreness',
      'Hold on tender spots',
    ]),
    tips: JSON.stringify(['Avoid bones', 'Slow and controlled', 'Hydrate']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Dynamic Stretching',
    description: 'Active stretching to warm up before workouts',
    category: VideoCategory.MOBILITY,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=yc0oQJ-hJUU',
    thumbnailUrl: 'https://example.com/dynamic-stretch.jpg',
    equipment: JSON.stringify(['None']),
    muscleGroups: JSON.stringify(['Full Body']),
    tags: JSON.stringify(['warm-up', 'mobility', 'pre-workout']),
    instructions: JSON.stringify(['Leg swings forward/back', 'Arm circles', 'Walking lunges with twist', 'Inchworms']),
    tips: JSON.stringify(['Controlled movements', 'Increase range gradually', 'Build heart rate']),
    coach: { connect: { id: '' } },
  },

  // PILATES
  {
    title: 'Pilates Core',
    description: 'Fundamental pilates exercises for core strength',
    category: VideoCategory.PILATES,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 1200,
    videoUrl: 'https://www.youtube.com/watch?v=SJRw9u2L9t0',
    thumbnailUrl: 'https://example.com/pilates-core.jpg',
    equipment: JSON.stringify(['Mat']),
    muscleGroups: JSON.stringify(['Core', 'Stabilizers']),
    tags: JSON.stringify(['pilates', 'core', 'beginner']),
    instructions: JSON.stringify([
      'Engage deep core',
      'Controlled breathing',
      'Precision of movement',
      'Full range of motion',
    ]),
    tips: JSON.stringify(['Quality over quantity', 'Engage before moving', 'Neutral spine']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Advanced Pilates Core',
    description: 'Challenge your core with advanced pilates movements',
    category: VideoCategory.PILATES,
    difficulty: DifficultyLevel.ADVANCED,
    duration: 1500,
    videoUrl: 'https://www.youtube.com/watch?v=K56Z12j1Uw4',
    thumbnailUrl: 'https://example.com/thumb5.jpg',
    equipment: JSON.stringify(['Pilates Mat', 'Pilates Ball']),
    muscleGroups: JSON.stringify(['Core', 'Stabilizers']),
    tags: JSON.stringify(['pilates', 'core', 'advanced']),
    instructions: JSON.stringify([
      'Engage core throughout',
      'Control every movement',
      'Focus on precision',
      'Maintain neutral spine',
    ]),
    tips: JSON.stringify(['Quality over speed', 'Engage deep abdominals', "Don't hold your breath"]),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Reformer Pilates',
    description: 'Full-body pilates using the reformer machine',
    category: VideoCategory.PILATES,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 1500,
    videoUrl: 'https://www.youtube.com/watch?v=yxQ-xNFLaLg',
    thumbnailUrl: 'https://example.com/reformer.jpg',
    equipment: JSON.stringify(['Pilates Reformer']),
    muscleGroups: JSON.stringify(['Full Body', 'Core']),
    tags: JSON.stringify(['pilates', 'full-body', 'machine']),
    instructions: JSON.stringify([
      'Set resistance appropriately',
      'Smooth, controlled movements',
      'Maintain proper alignment',
      'Focus on breath',
    ]),
    tips: JSON.stringify(['Less is more', 'Quality form', 'Full range']),
    coach: { connect: { id: '' } },
  },

  // SPECIALTY
  {
    title: 'Strength Training Basics',
    description: 'Learn proper form for fundamental strength exercises',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 2400,
    videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    thumbnailUrl: 'https://example.com/thumb3.jpg',
    equipment: JSON.stringify(['Dumbbells', 'Resistance Bands']),
    muscleGroups: JSON.stringify(['Arms', 'Legs', 'Core', 'Back']),
    tags: JSON.stringify(['strength', 'basics', 'form']),
    instructions: JSON.stringify([
      'Start with bodyweight movements',
      'Add resistance gradually',
      'Focus on proper form',
      'Rest between sets',
    ]),
    tips: JSON.stringify(['Quality over quantity', 'Start with lighter weights', 'Progress gradually']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Battle Ropes',
    description: 'High-intensity training with battle ropes',
    category: VideoCategory.CARDIO,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 900,
    videoUrl: 'https://www.youtube.com/watch?v=9p8CPBXz7Jc',
    thumbnailUrl: 'https://example.com/battle-ropes.jpg',
    equipment: JSON.stringify(['Battle Ropes']),
    muscleGroups: JSON.stringify(['Shoulders', 'Arms', 'Cardiovascular', 'Core']),
    tags: JSON.stringify(['cardio', 'intensity', 'shoulders']),
    instructions: JSON.stringify([
      'Feet shoulder-width apart',
      'Rapid up-down wave motion',
      'Full body engagement',
      'Alternate patterns',
    ]),
    tips: JSON.stringify(['Stay engaged', 'Rhythmic motion', 'Increase intensity gradually']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Kettlebell Swings',
    description: 'Explosive full-body power and conditioning',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.INTERMEDIATE,
    duration: 900,
    videoUrl: 'https://www.youtube.com/watch?v=M4sPfYKvXxU',
    thumbnailUrl: 'https://example.com/kettlebell-swing.jpg',
    equipment: JSON.stringify(['Kettlebell']),
    muscleGroups: JSON.stringify(['Glutes', 'Hamstrings', 'Shoulders', 'Core']),
    tags: JSON.stringify(['strength', 'power', 'full-body']),
    instructions: JSON.stringify([
      'Hinge at hips with kettlebell',
      'Explosive hip extension',
      'Swing to shoulder height',
      'Control descent',
    ]),
    tips: JSON.stringify(['Hip drive', 'Not arm movement', 'Explosive power']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Box Jumps',
    description: 'Build explosive leg power with plyometrics',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.ADVANCED,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=2YVN1WiI15w',
    thumbnailUrl: 'https://example.com/box-jump.jpg',
    equipment: JSON.stringify(['Plyo Box']),
    muscleGroups: JSON.stringify(['Legs', 'Glutes', 'Power']),
    tags: JSON.stringify(['plyometrics', 'power', 'legs']),
    instructions: JSON.stringify([
      'Stand facing box',
      'Rapid squat and jump',
      'Land softly on box',
      'Step down safely',
    ]),
    tips: JSON.stringify(['Soft landing', 'Explosive power', 'Start with lower box']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Push-ups',
    description: 'Master the classic bodyweight exercise',
    category: VideoCategory.STRENGTH_TRAINING,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    thumbnailUrl: 'https://example.com/push-ups.jpg',
    equipment: JSON.stringify(['None']),
    muscleGroups: JSON.stringify(['Chest', 'Shoulders', 'Triceps', 'Core']),
    tags: JSON.stringify(['strength', 'chest', 'bodyweight']),
    instructions: JSON.stringify([
      'Plank position',
      'Lower body until chest nearly touches',
      'Press back up',
      'Keep body straight',
    ]),
    tips: JSON.stringify(['Full range', 'Tight core', 'Control descent']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Burpees',
    description: 'Full-body explosive cardio and strength combo',
    category: VideoCategory.CARDIO,
    difficulty: DifficultyLevel.ADVANCED,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=cEF7EKVb0Ek',
    thumbnailUrl: 'https://example.com/burpees.jpg',
    equipment: JSON.stringify(['None']),
    muscleGroups: JSON.stringify(['Full Body', 'Cardiovascular', 'Strength']),
    tags: JSON.stringify(['cardio', 'strength', 'full-body']),
    instructions: JSON.stringify([
      'Stand upright',
      'Drop to plank',
      'Do push-up',
      'Jump back to stand',
      'Jump in the air',
    ]),
    tips: JSON.stringify(['Modify if needed', 'Full effort', 'Good form matters']),
    coach: { connect: { id: '' } },
  },
  {
    title: 'Mountain Climbers',
    description: 'Core and cardio conditioning exercise',
    category: VideoCategory.CARDIO,
    difficulty: DifficultyLevel.BEGINNER,
    duration: 600,
    videoUrl: 'https://www.youtube.com/watch?v=nmwgirgXLYM',
    thumbnailUrl: 'https://example.com/mountain-climbers.jpg',
    equipment: JSON.stringify(['None']),
    muscleGroups: JSON.stringify(['Core', 'Cardiovascular', 'Shoulders']),
    tags: JSON.stringify(['cardio', 'core', 'conditioning']),
    instructions: JSON.stringify([
      'Plank position',
      'Drive knees toward chest alternately',
      'Maintain steady pace',
      'Keep hips level',
    ]),
    tips: JSON.stringify(['Fast pace', 'Level hips', 'Steady breathing']),
    coach: { connect: { id: '' } },
  },
];

async function seedVideos() {
  try {
    const coach = await prisma.user.findFirst({
      where: { role: 'COACH' },
      select: { id: true },
    });

    if (!coach) {
      throw new Error('No coach found (role=COACH). Create a coach user first.');
    }

    await prisma.video.deleteMany({});

    const data = sampleVideos.map(v => ({
      ...v,
      coach: { connect: { id: coach.id } },
    }));

    await prisma.video.createMany({
      data: data.map(({ coach, ...rest }) => rest as Prisma.VideoCreateManyInput),
    });

    console.log('✅ Sample videos seeded successfully!');
  } catch (error) {
    console.error('Error seeding videos:', error);
    process.exitCode = 1;
  } finally {
    await prisma.$disconnect();
  }
}

seedVideos();
